import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { NavLink } from 'react-router-dom';
const MobileNavbar = () => {
    const [menuOpen, setMenuOpen] = useState(false);
    const toggleMenu = () => {
        setMenuOpen(!menuOpen);
    };
    const NavLinks = (_jsxs(_Fragment, { children: [_jsx("ol", { children: _jsx(NavLink, { to: "/", className: ({ isActive, isPending }) => isPending ? "pending" : isActive ? "underline text-[#3C43D1]" : "", children: "Home" }) }), _jsx("ol", { children: _jsx(NavLink, { to: "/products", className: ({ isActive, isPending }) => isPending ? "pending" : isActive ? "underline text-[#3C43D1]" : "", children: "Products" }) }), _jsx("ol", { children: _jsx(NavLink, { to: "/myCart", className: ({ isActive, isPending }) => isPending ? "pending" : isActive ? "underline text-[#3C43D1]" : "", children: "MyCart" }) }), _jsx("ol", { children: _jsx(NavLink, { to: "/productManagement", className: ({ isActive, isPending }) => isPending ? "pending" : isActive ? "underline text-[#3C43D1]" : "", children: "Product Management" }) }), _jsx("ol", { children: _jsx(NavLink, { to: "/about", className: ({ isActive, isPending }) => isPending ? "pending" : isActive ? "underline text-[#3C43D1]" : "", children: "About" }) })] }));
    return (_jsxs("nav", { className: "bg-white shadow-md  lg:hidden", children: [_jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: _jsx("div", { className: "flex items-center justify-between h-16", children: _jsxs("div", { className: "flex lg:hidden", children: [_jsxs("button", { onClick: toggleMenu, type: "button", className: "inline-flex items-center justify-center p-2 rounded-md text-gray-900 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white", "aria-controls": "mobile-menu", "aria-expanded": "false", children: [_jsx("svg", { className: `${menuOpen ? 'hidden' : 'block'} h-3 w-3`, xmlns: "http://www.w3.org/2000/svg", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", "aria-hidden": "true", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M4 6h16M4 12h16m-7 6h7" }) }), _jsx("svg", { className: `${menuOpen ? 'block' : 'hidden'} h-3 w-3`, xmlns: "http://www.w3.org/2000/svg", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", "aria-hidden": "true", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M6 18L18 6M6 6l12 12" }) })] }), _jsx("div", { className: 'h-6 w-20 ml-36 md:ml-60', children: _jsx("img", { src: "https://welldone.axiomthemes.com/wp-content/uploads/2024/04/logo-3.png", alt: "" }) })] }) }) }), _jsx("div", { className: `${menuOpen ? 'block' : 'hidden'} lg:hidden`, id: "mobile-menu", children: _jsx("div", { className: "px-2 pt-2 pb-3 space-y-1 mx-auto sm:px-3", children: NavLinks }) })] }));
};
export default MobileNavbar;
